package com.hsy.flightpacket.bean.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEACH_ACTIVITY_CHILD".
*/
public class TeachActivityChildDao extends AbstractDao<TeachActivityChild, Long> {

    public static final String TABLENAME = "TEACH_ACTIVITY_CHILD";

    /**
     * Properties of entity TeachActivityChild.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Lianxihao = new Property(1, String.class, "lianxihao", false, "LIANXIHAO");
        public final static Property Cishu = new Property(2, String.class, "cishu", false, "CISHU");
        public final static Property Zhengjia = new Property(3, String.class, "zhengjia", false, "ZHENGJIA");
        public final static Property Fujia = new Property(4, String.class, "fujia", false, "FUJIA");
        public final static Property Gaodu = new Property(5, String.class, "gaodu", false, "GAODU");
        public final static Property Hangxianhao = new Property(6, String.class, "hangxianhao", false, "HANGXIANHAO");
        public final static Property Jiayou = new Property(7, Boolean.class, "jiayou", false, "JIAYOU");
        public final static Property Teachactivityid = new Property(8, Long.class, "teachactivityid", false, "TEACHACTIVITYID");
    };


    public TeachActivityChildDao(DaoConfig config) {
        super(config);
    }
    
    public TeachActivityChildDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEACH_ACTIVITY_CHILD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LIANXIHAO\" TEXT," + // 1: lianxihao
                "\"CISHU\" TEXT," + // 2: cishu
                "\"ZHENGJIA\" TEXT," + // 3: zhengjia
                "\"FUJIA\" TEXT," + // 4: fujia
                "\"GAODU\" TEXT," + // 5: gaodu
                "\"HANGXIANHAO\" TEXT," + // 6: hangxianhao
                "\"JIAYOU\" INTEGER," + // 7: jiayou
                "\"TEACHACTIVITYID\" INTEGER);"); // 8: teachactivityid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEACH_ACTIVITY_CHILD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TeachActivityChild entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lianxihao = entity.getLianxihao();
        if (lianxihao != null) {
            stmt.bindString(2, lianxihao);
        }
 
        String cishu = entity.getCishu();
        if (cishu != null) {
            stmt.bindString(3, cishu);
        }
 
        String zhengjia = entity.getZhengjia();
        if (zhengjia != null) {
            stmt.bindString(4, zhengjia);
        }
 
        String fujia = entity.getFujia();
        if (fujia != null) {
            stmt.bindString(5, fujia);
        }
 
        String gaodu = entity.getGaodu();
        if (gaodu != null) {
            stmt.bindString(6, gaodu);
        }
 
        String hangxianhao = entity.getHangxianhao();
        if (hangxianhao != null) {
            stmt.bindString(7, hangxianhao);
        }
 
        Boolean jiayou = entity.getJiayou();
        if (jiayou != null) {
            stmt.bindLong(8, jiayou ? 1L: 0L);
        }
 
        Long teachactivityid = entity.getTeachactivityid();
        if (teachactivityid != null) {
            stmt.bindLong(9, teachactivityid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TeachActivityChild entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lianxihao = entity.getLianxihao();
        if (lianxihao != null) {
            stmt.bindString(2, lianxihao);
        }
 
        String cishu = entity.getCishu();
        if (cishu != null) {
            stmt.bindString(3, cishu);
        }
 
        String zhengjia = entity.getZhengjia();
        if (zhengjia != null) {
            stmt.bindString(4, zhengjia);
        }
 
        String fujia = entity.getFujia();
        if (fujia != null) {
            stmt.bindString(5, fujia);
        }
 
        String gaodu = entity.getGaodu();
        if (gaodu != null) {
            stmt.bindString(6, gaodu);
        }
 
        String hangxianhao = entity.getHangxianhao();
        if (hangxianhao != null) {
            stmt.bindString(7, hangxianhao);
        }
 
        Boolean jiayou = entity.getJiayou();
        if (jiayou != null) {
            stmt.bindLong(8, jiayou ? 1L: 0L);
        }
 
        Long teachactivityid = entity.getTeachactivityid();
        if (teachactivityid != null) {
            stmt.bindLong(9, teachactivityid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TeachActivityChild readEntity(Cursor cursor, int offset) {
        TeachActivityChild entity = new TeachActivityChild( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // lianxihao
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cishu
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // zhengjia
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fujia
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gaodu
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // hangxianhao
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // jiayou
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // teachactivityid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TeachActivityChild entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLianxihao(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCishu(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setZhengjia(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFujia(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGaodu(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setHangxianhao(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJiayou(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setTeachactivityid(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TeachActivityChild entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TeachActivityChild entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
